// Builds precompiled-containers/ by driving the `precompile` Lambda.
//
// The DI container cache key contains the absolute paths inside the deployment
// package, so the containers can only be produced by the deployed function itself -
// hence the two-phase deploy: deploy, precompile, deploy again.
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LambdaClient, InvokeCommand } from '@aws-sdk/client-lambda';

const FUNCTION = process.env.PRECOMPILE_FUNCTION ?? 'phpstan-runner-prod-precompile';
const OUT = 'precompiled-containers';
const CHUNK = 24;

const levels = Array.from({ length: 11 }, (_, i) => String(i));
const versions = [70200, 70300, 70400, 80000, 80100, 80200, 80300, 80400, 80500];
const flags = [];
for (const strictRules of [false, true]) {
	for (const bleedingEdge of [false, true]) {
		for (const treatPhpDocTypesAsCertain of [true, false]) {
			flags.push({ strictRules, bleedingEdge, treatPhpDocTypesAsCertain });
		}
	}
}

const combos = flags.flatMap((f) => levels.flatMap((level) => versions.map((phpVersion) => ({ level, phpVersion, ...f }))));

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const lambda = new LambdaClient({ region: process.env.AWS_DEFAULT_REGION ?? 'eu-west-1' });
const index = {};
const started = Date.now();

for (let i = 0; i < combos.length; i += CHUNK) {
	const chunk = combos.slice(i, i + CHUNK);
	const res = await lambda.send(new InvokeCommand({
		FunctionName: FUNCTION,
		Payload: Buffer.from(JSON.stringify({ combos: chunk })),
	}));
	const body = JSON.parse(Buffer.from(res.Payload).toString());
	if (res.FunctionError || body.error) {
		console.error('precompile failed:', JSON.stringify(body).slice(0, 2000));
		process.exit(1);
	}
	for (const [name, b64] of Object.entries(body.files)) {
		writeFileSync(join(OUT, `${name}.php.gz`), Buffer.from(b64, 'base64'));
	}
	Object.assign(index, body.index);
	console.log(`  [${Math.min(i + CHUNK, combos.length)}/${combos.length}] ${Object.keys(index).length} containers`);
}

const lines = Object.keys(index).sort().map((k) => `\t'${k}' => '${index[k]}',`);
writeFileSync(
	join(OUT, 'index.php'),
	`<?php declare(strict_types = 1);\n\n// Generated by precompile.mjs - maps a request's config hash to its DI container.\n\nreturn [\n${lines.join('\n')}\n];\n`,
);

console.log(`precompiled ${Object.keys(index).length} containers in ${Math.round((Date.now() - started) / 1000)}s`);
