name: Feature request 🚀
description: I have a suggestion (and may want to implement it 🙂)!

body:
  - type: textarea
    attributes:
      label: Feature request
      description: Please provide a clear description of what problem you are trying to solve and how would you want it to be solved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Did PHPStan help you today? Did it make you happy in any way?
      description: |
        Answering this question is not required, but if you have anything positive to share, please do so here!
        Sometimes we get tired of reading bug reports all day and a little positive end note does wonders.
        [Idea by Joey Hess](https://joeyh.name/blog/entry/two_holiday_stories/)
