name: "Algolia Crawler Config Update"

on:
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/algolia-crawler-config.json'
      - '.github/workflows/algolia-crawler-config.yml'

permissions:
  contents: read

jobs:
  update-config:
    name: "Update Algolia Crawler Config"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: "Update Crawler Config"
        run: |
          jq --arg key "${{ secrets.ALGOLIA_CRAWLER_CRAWLER_API_KEY }}" '.apiKey = $key' .github/workflows/algolia-crawler-config.json | \
          curl -X PATCH "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/config" \
            -H "Content-Type: application/json" \
            -u "${{ secrets.ALGOLIA_CRAWLER_USER_ID }}:${{ secrets.ALGOLIA_CRAWLER_API_KEY }}" \
            -d @-

      - name: "Trigger Crawler Reindex"
        run: |
          curl -X POST "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/reindex" \
            -H "Content-Type: application/json" \
            -u "${{ secrets.ALGOLIA_CRAWLER_USER_ID }}:${{ secrets.ALGOLIA_CRAWLER_API_KEY }}"
