# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build Identifier Extractor"

on:
  pull_request:
    paths:
      - 'identifier-extractor/**'
      - '.github/workflows/build-identifier-extractor.yml'
  push:
    branches:
      - "2.2.x"
    paths:
      - 'identifier-extractor/**'
      - '.github/workflows/build-identifier-extractor.yml'

permissions:
  contents: read

jobs:
  build-identifier-extractor:
    name: "Build Identifier Extractor"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Install Extractor dependencies"
        uses: "ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520" # v3
        with:
          working-directory: "identifier-extractor"

      - name: "PHPStan"
        working-directory: "identifier-extractor"
        run: ../phpstan
