name: "Claude Update Error Docs"

on:
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/claude-update-error-docs-identifiers-change.yml'
      - 'website/src/errorsIdentifiers.json'

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Trigger Claude Update Error Docs
        env:
          GH_TOKEN: ${{ secrets.PHPSTAN_BOT_TOKEN }}
        run: gh workflow run claude-update-error-docs.yml -f sha=${{ github.sha }} --repo phpstan-bot/phpstan
