# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integration tests"

on:
  pull_request:
    paths:
      - '.github/workflows/integration-tests.yml'
      - '.github/workflows/integration-tests-run.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/integration-tests.yml'
      - '.github/workflows/integration-tests-run.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

jobs:
  upload-phar:
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: phar-file
          path: phpstan.phar
  integration-tests:
    needs: upload-phar
    uses: ./.github/workflows/integration-tests.yml
    with:
      ref: ${{ github.ref }}
      phar-checksum: "always"
    secrets:
      phpstan-bot-token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
