name: 'Lock Issues'

on:
  schedule:
    - cron: '2 1 * * *'

concurrency: lock_issues

permissions:
  contents: read

jobs:
  lock:
    permissions:
      issues: write  # for dessant/lock-threads to lock issues
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.0.1
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '31'
          exclude-issue-created-before: ''
          exclude-any-issue-labels: ''
          add-issue-labels: ''
          issue-comment: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs.
          issue-lock-reason: 'resolved'
          process-only: 'issues'
