# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Other tests"

on:
  pull_request:
    paths:
      - '.github/workflows/other-tests.yml'
      - '.github/workflows/other-tests-run.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/other-tests.yml'
      - '.github/workflows/other-tests-run.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

jobs:
  upload-phar:
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: phar-file
          path: phpstan.phar
  other-tests:
    needs: upload-phar
    uses: ./.github/workflows/other-tests.yml
    with:
      ref: ${{ github.ref }}
      phar-checksum: "always"
