# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Create release"

on:
  push:
    tags:
      - '*'

concurrency: release

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Create release"
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        id: release
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          draft: true
          discussion_category_name: "General"
          files: |
            phpstan.phar
            phpstan.phar.asc

      - name: "Print release URL"
        run: echo "${{ steps.release.outputs.url }}" >> "$GITHUB_STEP_SUMMARY"
