# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Spelling"

on:
  pull_request:
  push:
    branches:
      - "2.3.x"

permissions:
  contents: read

jobs:
  typos:
    name: "Check for typos"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Check for typos"
        uses: "crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14" # v1.48.0
        with:
          files: "README.md website/"
