# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Spelling"

on:
  pull_request:
  push:
    branches:
      - "2.3.x"

permissions:
  contents: read

jobs:
  typos:
    name: "Check for typos"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: "Check for typos"
        uses: "crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b" # v1.50.1
        with:
          files: "README.md website/"
