# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Generate Sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: 15 14 * * *
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/sponsors.yml'
      - 'BACKERS.md'

jobs:
  sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      -
        name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PHPSTANBOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PHPSTANBOT_KEY_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}

      - name: "Construct template"
        id: template
        run: |
          echo "text<<MESSAGE" >> "$GITHUB_OUTPUT"
          echo '<li><a href="https://github.com/{{{ login }}}">{{{ name }}} ({{{ login }}})</a></li>' >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo 'MESSAGE' >> "$GITHUB_OUTPUT"

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 500
          maximum: 2999
          marker: 'indi'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 500
          maximum: 2999
          organization: true
          marker: 'indi-org'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 3000
          maximum: 9999
          marker: 'small'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 3000
          maximum: 9999
          organization: true
          marker: 'small-org'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 10000
          maximum: 32999
          marker: 'bronze'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 10000
          maximum: 32999
          organization: true
          marker: 'bronze-org'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 33000
          maximum: 49999
          marker: 'silver'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 33000
          maximum: 49999
          organization: true
          marker: 'silver-org'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 50000
          marker: 'gold'
          template: ${{ steps.template.outputs.text }}

      - name: Generate Sponsors
        uses: ondrejmirtes/github-sponsors-readme-action@9fd59795af9477235df8f234f962ef3dd854592f # v1.2.2.3
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: 'BACKERS.md'
          minimum: 50000
          organization: true
          marker: 'gold-org'
          template: ${{ steps.template.outputs.text }}

      - name: "Commit changes"
        uses: "stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9" # v7.1.0
        id: "commit"
        with:
          commit_message: "Update BACKERS.md"
          commit_user_name: "phpstan-bot"
          commit_user_email: "ondrej+phpstanbot@mirtes.cz"
          commit_author: "phpstan-bot <ondrej+phpstanbot@mirtes.cz>"
          commit_options: "--gpg-sign"

      - name: "Slack Notification"
        if: steps.commit.outputs.changes_detected == 'true'
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_CHANNEL: sponsors
          SLACK_MESSAGE: 'https://github.com/phpstan/phpstan/commit/${{ steps.commit.outputs.commit_hash }}'
          SLACK_TITLE: Sponsors changed!
          SLACK_USERNAME: phpstan
          SLACK_WEBHOOK: ${{ secrets.SLACK_SPONSORS_WEBHOOK }}
          MSG_MINIMAL: true
