# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Test projects"

on:
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/test-projects.yml'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

permissions:
  contents: read

jobs:
  test-projects:
    name: "Test projects"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        repository:
          - "phpstan/lorem"
          - "phpstan/ipsum"
          - "phpstan/dolor"
          - "packagist/private-packagist"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: "${{ matrix.repository }}"
          event-type: test_phpstan
          client-payload: '{"ref": "${{ github.ref_name }}"}'
