# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/tests.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

permissions:
  contents: read

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: "Install PHP"
        uses: "shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1" # v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          extensions: mbstring

      - uses: "ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520" # v3

      - name: "Tests"
        run: |
          cd e2e
          composer install --ignore-platform-reqs
          # php testPharAutoloader.php
          vendor/bin/phpunit PharTest.php
