# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/tests.yml'
      - 'e2e/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

permissions:
  contents: read

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          extensions: mbstring

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Tests"
        run: |
          cd e2e
          composer install --ignore-platform-reqs
          # php testPharAutoloader.php
          vendor/bin/phpunit PharTest.php
