# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update playground runner"

on:
  workflow_dispatch:
  push:
    branches:
      - "2.2.x"
    paths:
      - '.github/workflows/update-playground-runner.yml'
      - 'playground-runner/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

concurrency: playground_runner

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2

      - name: "Install Node"
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: playground-runner/package-lock.json

      - name: "Install dependencies"
        working-directory: ./playground-runner
        run: "npm ci"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # 2.37.2
        with:
          coverage: "none"
          php-version: "8.5"

      - name: "Install playground runner dependencies"
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0
        with:
          working-directory: "playground-runner"

      - name: "Preflight playground.neon"
        working-directory: ./playground-runner
        run: |
          touch empty.php
          ../phpstan analyse -c playground.neon -l 8 empty.php

      - name: "Analyse"
        working-directory: ./playground-runner
        run: "../phpstan"

      - name: "Copy current PHAR"
        working-directory: ./playground-runner
        run: |
          cp ../phpstan.phar vendor/phpstan/phpstan/phpstan.phar && \
          cp ../phpstan vendor/phpstan/phpstan/phpstan && \
          cp ../bootstrap.php vendor/phpstan/phpstan/bootstrap.php

      - name: "Clean Git directory"
        working-directory: ./playground-runner
        run: rm -rf vendor/phpstan/phpstan/.git

      - name: "Deploy"
        working-directory: ./playground-runner
        env:
          AWS_DEFAULT_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.PLAYGROUND_RUNNER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PLAYGROUND_RUNNER_AWS_SECRET_ACCESS_KEY }}
        run: "npm run deploy"
