# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update playground API"

on:
  push:
    branches:
      - "2.3.x"
    paths:
      - '.github/workflows/update-playground-api.yml'
      - 'playground-api/**'

concurrency: playground_api

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: "Install Node"
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: playground-api/package-lock.json

      - name: "Install dependencies"
        working-directory: ./playground-api
        run: "npm ci"

      - name: "Check"
        working-directory: ./playground-api
        run: "npm run check"

      - name: "Deploy"
        working-directory: ./playground-api
        env:
          AWS_DEFAULT_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.PLAYGROUND_RUNNER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PLAYGROUND_RUNNER_AWS_SECRET_ACCESS_KEY }}
        run: "npm run deploy"
